services:
  - type: web
    name: personal-finance-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn app:app

disks:
  - name: data
    mountPath: /opt/data
    sizeGB: 1
